{
    "Control Points":
    [
        {
            "IsoValue":0,
            "Opacity":0,
            "Style":0
        },
        {
            "IsoValue":27,
            "Opacity":0,
            "Style":17
        },
        {
            "IsoValue":31,
            "Opacity":62,
            "Style":27
        },
        {
            "IsoValue":43,
            "Opacity":67,
            "Style":27
        },
        {
            "IsoValue":47,
            "Opacity":0,
            "Style":26
        },
        {
            "IsoValue":51,
            "Opacity":68,
            "Style":26
        },
        {
            "IsoValue":61,
            "Opacity":64,
            "Style":26
        },
        {
            "IsoValue":70,
            "Opacity":0,
            "Style":1
        },
        {
            "IsoValue":73,
            "Opacity":159,
            "Style":0
        },
        {
            "IsoValue":94,
            "Opacity":159,
            "Style":0
        },
        {
            "IsoValue":103,
            "Opacity":0,
            "Style":0
        },
        {
            "IsoValue":106,
            "Opacity":255,
            "Style":0
        },
        {
            "IsoValue":255,
            "Opacity":255,
            "Style":0
        }
    ]
}