{
    "Control Points":
    [
        {
            "IsoValue":0,
            "Opacity":0,
            "Style":0
        },
        {
            "IsoValue":45,
            "Opacity":0,
            "Style":29
        },
        {
            "IsoValue":255,
            "Opacity":255,
            "Style":4
        }
    ]
}