{
    "Control Points":
    [
        {
            "IsoValue":0,
            "Opacity":0,
            "Style":0
        },
        {
            "IsoValue":23,
            "Opacity":0,
            "Style":1
        },
        {
            "IsoValue":24,
            "Opacity":29,
            "Style":17
        },
        {
            "IsoValue":29,
            "Opacity":0,
            "Style":27
        },
        {
            "IsoValue":41,
            "Opacity":24,
            "Style":27
        },
        {
            "IsoValue":51,
            "Opacity":0,
            "Style":13
        },
        {
            "IsoValue":55,
            "Opacity":211,
            "Style":19
        },
        {
            "IsoValue":83,
            "Opacity":201,
            "Style":8
        },
        {
            "IsoValue":96,
            "Opacity":0,
            "Style":4
        },
        {
            "IsoValue":105,
            "Opacity":216,
            "Style":4
        },
        {
            "IsoValue":249,
            "Opacity":233,
            "Style":4
        },
        {
            "IsoValue":255,
            "Opacity":0,
            "Style":4
        }
    ]
}